//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int MaDanhGiaSanPham { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
        public int DangDiem { get; set; }
        public string NoiDungDanhGia { get; set; }
    }
}
