//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public int MaDonHang { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<double> TongGia { get; set; }
        public Nullable<double> PhiVanChuyen { get; set; }
        public Nullable<int> TrangThaiThanhToan { get; set; }
        public Nullable<System.DateTime> NgayDuKienGiaoHang { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string TrangThaiDonHang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string MaVoucher { get; set; }
        public Nullable<double> TongTienSauKhiGiamGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
