//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int Mafeedback { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaChiTietDH { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGianfeedback { get; set; }
        public Nullable<double> DanhGia { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
