//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaGioHang { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaChiTietSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual ChiTietSanPham ChiTietSanPham { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
