//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int MaHinhAnh { get; set; }
        public Nullable<int> MaSp { get; set; }
        public string hinhanh1 { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
