//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_SHOPTHOITRANG_DOANEntities : DbContext
    {
        public QL_SHOPTHOITRANG_DOANEntities()
            : base("name=QL_SHOPTHOITRANG_DOANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALAMVIEC> CALAMVIEC { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DbSet<ChiTietSanPham> ChiTietSanPham { get; set; }
        public virtual DbSet<ChucNang> ChucNang { get; set; }
        public virtual DbSet<DanhMuc> DanhMuc { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
        public virtual DbSet<HinhAnh> HinhAnh { get; set; }
        public virtual DbSet<KichThuoc> KichThuoc { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<MauSac> MauSac { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<OTP> OTP { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyen { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VOUCHER> VOUCHER { get; set; }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai")]
        public virtual IQueryable<LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai_Result> LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai(Nullable<System.DateTime> thoiGianBatDau, Nullable<System.DateTime> thoiGianKetThuc, string trangThaiDonHang, string hinhThucThanhToan, Nullable<int> maKhachHang, string trangThaiThanhToan, Nullable<decimal> giaMin, Nullable<decimal> giaMax)
        {
            var thoiGianBatDauParameter = thoiGianBatDau.HasValue ?
                new ObjectParameter("ThoiGianBatDau", thoiGianBatDau) :
                new ObjectParameter("ThoiGianBatDau", typeof(System.DateTime));
    
            var thoiGianKetThucParameter = thoiGianKetThuc.HasValue ?
                new ObjectParameter("ThoiGianKetThuc", thoiGianKetThuc) :
                new ObjectParameter("ThoiGianKetThuc", typeof(System.DateTime));
    
            var trangThaiDonHangParameter = trangThaiDonHang != null ?
                new ObjectParameter("TrangThaiDonHang", trangThaiDonHang) :
                new ObjectParameter("TrangThaiDonHang", typeof(string));
    
            var hinhThucThanhToanParameter = hinhThucThanhToan != null ?
                new ObjectParameter("HinhThucThanhToan", hinhThucThanhToan) :
                new ObjectParameter("HinhThucThanhToan", typeof(string));
    
            var maKhachHangParameter = maKhachHang.HasValue ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(int));
    
            var trangThaiThanhToanParameter = trangThaiThanhToan != null ?
                new ObjectParameter("TrangThaiThanhToan", trangThaiThanhToan) :
                new ObjectParameter("TrangThaiThanhToan", typeof(string));
    
            var giaMinParameter = giaMin.HasValue ?
                new ObjectParameter("GiaMin", giaMin) :
                new ObjectParameter("GiaMin", typeof(decimal));
    
            var giaMaxParameter = giaMax.HasValue ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai_Result>("[QL_SHOPTHOITRANG_DOANEntities].[LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai](@ThoiGianBatDau, @ThoiGianKetThuc, @TrangThaiDonHang, @HinhThucThanhToan, @MaKhachHang, @TrangThaiThanhToan, @GiaMin, @GiaMax)", thoiGianBatDauParameter, thoiGianKetThucParameter, trangThaiDonHangParameter, hinhThucThanhToanParameter, maKhachHangParameter, trangThaiThanhToanParameter, giaMinParameter, giaMaxParameter);
        }
    }
}
