//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaNV { get; set; }
        public int MaChucNang { get; set; }
        public string Note { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
