//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_SHOPTHOITRANG_DOANEntities : DbContext
    {
        public QL_SHOPTHOITRANG_DOANEntities()
            : base("name=QL_SHOPTHOITRANG_DOANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DbSet<ChiTietSanPham> ChiTietSanPham { get; set; }
        public virtual DbSet<ChucNang> ChucNang { get; set; }
        public virtual DbSet<DanhMuc> DanhMuc { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
        public virtual DbSet<HinhAnh> HinhAnh { get; set; }
        public virtual DbSet<KichThuoc> KichThuoc { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<MauSac> MauSac { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyen { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VOUCHER> VOUCHER { get; set; }
        public virtual DbSet<VOUCHER_KHACHHANG> VOUCHER_KHACHHANG { get; set; }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "FeedBack_SanPham")]
        public virtual IQueryable<FeedBack_SanPham_Result> FeedBack_SanPham(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FeedBack_SanPham_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[FeedBack_SanPham](@MaSP)", maSPParameter);
        }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "LaySanPhamDuocDatNhieuNhat_top8")]
        public virtual IQueryable<LaySanPhamDuocDatNhieuNhat_top8_Result> LaySanPhamDuocDatNhieuNhat_top8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LaySanPhamDuocDatNhieuNhat_top8_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[LaySanPhamDuocDatNhieuNhat_top8]()");
        }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai")]
        public virtual IQueryable<LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai_Result> LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai(Nullable<System.DateTime> thoiGianBatDau, Nullable<System.DateTime> thoiGianKetThuc, string trangThaiDonHang, string hinhThucThanhToan, Nullable<int> maKhachHang, string trangThaiThanhToan, Nullable<decimal> giaMin, Nullable<decimal> giaMax)
        {
            var thoiGianBatDauParameter = thoiGianBatDau.HasValue ?
                new ObjectParameter("ThoiGianBatDau", thoiGianBatDau) :
                new ObjectParameter("ThoiGianBatDau", typeof(System.DateTime));
    
            var thoiGianKetThucParameter = thoiGianKetThuc.HasValue ?
                new ObjectParameter("ThoiGianKetThuc", thoiGianKetThuc) :
                new ObjectParameter("ThoiGianKetThuc", typeof(System.DateTime));
    
            var trangThaiDonHangParameter = trangThaiDonHang != null ?
                new ObjectParameter("TrangThaiDonHang", trangThaiDonHang) :
                new ObjectParameter("TrangThaiDonHang", typeof(string));
    
            var hinhThucThanhToanParameter = hinhThucThanhToan != null ?
                new ObjectParameter("HinhThucThanhToan", hinhThucThanhToan) :
                new ObjectParameter("HinhThucThanhToan", typeof(string));
    
            var maKhachHangParameter = maKhachHang.HasValue ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(int));
    
            var trangThaiThanhToanParameter = trangThaiThanhToan != null ?
                new ObjectParameter("TrangThaiThanhToan", trangThaiThanhToan) :
                new ObjectParameter("TrangThaiThanhToan", typeof(string));
    
            var giaMinParameter = giaMin.HasValue ?
                new ObjectParameter("GiaMin", giaMin) :
                new ObjectParameter("GiaMin", typeof(decimal));
    
            var giaMaxParameter = giaMax.HasValue ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[LocDonHangTheoGioiGian_TongTien_MaKH_TrangThai](@ThoiGianBatDau, @ThoiGianKetThuc, @TrangThaiDonHang, @HinhThucThanhToan, @MaKhachHang, @TrangThaiThanhToan, @GiaMin, @GiaMax)", thoiGianBatDauParameter, thoiGianKetThucParameter, trangThaiDonHangParameter, hinhThucThanhToanParameter, maKhachHangParameter, trangThaiThanhToanParameter, giaMinParameter, giaMaxParameter);
        }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "ThongKeDoanhThuTheoNgay")]
        public virtual IQueryable<ThongKeDoanhThuTheoNgay_Result> ThongKeDoanhThuTheoNgay(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, string trangthai)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeDoanhThuTheoNgay_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[ThongKeDoanhThuTheoNgay](@startTime, @endTime, @trangthai)", startTimeParameter, endTimeParameter, trangthaiParameter);
        }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "ThongKeDoanhThuTheoThang")]
        public virtual IQueryable<ThongKeDoanhThuTheoThang_Result> ThongKeDoanhThuTheoThang(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string trangthai)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeDoanhThuTheoThang_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[ThongKeDoanhThuTheoThang](@startDate, @endDate, @trangthai)", startDateParameter, endDateParameter, trangthaiParameter);
        }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "ThongKeDonHangTheoThang_Huy")]
        public virtual IQueryable<ThongKeDonHangTheoThang_Huy_Result> ThongKeDonHangTheoThang_Huy(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string trangthai)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeDonHangTheoThang_Huy_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[ThongKeDonHangTheoThang_Huy](@startDate, @endDate, @trangthai)", startDateParameter, endDateParameter, trangthaiParameter);
        }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "ThongKeDonTheoNgay_Huy")]
        public virtual IQueryable<ThongKeDonTheoNgay_Huy_Result> ThongKeDonTheoNgay_Huy(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, string trangthai)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeDonTheoNgay_Huy_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[ThongKeDonTheoNgay_Huy](@startTime, @endTime, @trangthai)", startTimeParameter, endTimeParameter, trangthaiParameter);
        }
    
        [DbFunction("QL_SHOPTHOITRANG_DOANEntities", "ThongKeTopSanPhamNhieuNhatTrongGioHang")]
        public virtual IQueryable<ThongKeTopSanPhamNhieuNhatTrongGioHang_Result> ThongKeTopSanPhamNhieuNhatTrongGioHang(Nullable<int> soLuongTop)
        {
            var soLuongTopParameter = soLuongTop.HasValue ?
                new ObjectParameter("SoLuongTop", soLuongTop) :
                new ObjectParameter("SoLuongTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeTopSanPhamNhieuNhatTrongGioHang_Result>("[QL_SHOPTHOITRANG_DOANEntities1].[ThongKeTopSanPhamNhieuNhatTrongGioHang](@SoLuongTop)", soLuongTopParameter);
        }
    
        public virtual ObjectResult<LocSanPham_Result> LocSanPham(Nullable<int> maNhaCungCap, Nullable<int> maDanhMuc, Nullable<double> minPrice, Nullable<double> maxPrice, string sortByName, string sortByPrice)
        {
            var maNhaCungCapParameter = maNhaCungCap.HasValue ?
                new ObjectParameter("MaNhaCungCap", maNhaCungCap) :
                new ObjectParameter("MaNhaCungCap", typeof(int));
    
            var maDanhMucParameter = maDanhMuc.HasValue ?
                new ObjectParameter("MaDanhMuc", maDanhMuc) :
                new ObjectParameter("MaDanhMuc", typeof(int));
    
            var minPriceParameter = minPrice.HasValue ?
                new ObjectParameter("minPrice", minPrice) :
                new ObjectParameter("minPrice", typeof(double));
    
            var maxPriceParameter = maxPrice.HasValue ?
                new ObjectParameter("maxPrice", maxPrice) :
                new ObjectParameter("maxPrice", typeof(double));
    
            var sortByNameParameter = sortByName != null ?
                new ObjectParameter("sortByName", sortByName) :
                new ObjectParameter("sortByName", typeof(string));
    
            var sortByPriceParameter = sortByPrice != null ?
                new ObjectParameter("sortByPrice", sortByPrice) :
                new ObjectParameter("sortByPrice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocSanPham_Result>("LocSanPham", maNhaCungCapParameter, maDanhMucParameter, minPriceParameter, maxPriceParameter, sortByNameParameter, sortByPriceParameter);
        }
    
        public virtual ObjectResult<ThongKeTopSanPhamBanNhieuNhat_Result> ThongKeTopSanPhamBanNhieuNhat(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> soLuongTop, string trangthai)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var soLuongTopParameter = soLuongTop.HasValue ?
                new ObjectParameter("SoLuongTop", soLuongTop) :
                new ObjectParameter("SoLuongTop", typeof(int));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeTopSanPhamBanNhieuNhat_Result>("ThongKeTopSanPhamBanNhieuNhat", startTimeParameter, endTimeParameter, soLuongTopParameter, trangthaiParameter);
        }
    }
}
