//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER_KHACHHANG
    {
        public int MaKH { get; set; }
        public string MA_VOUCHER { get; set; }
        public string note { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
