//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOUCHER()
        {
            this.VOUCHER_KHACHHANG = new HashSet<VOUCHER_KHACHHANG>();
        }
    
        public string MA_VOUCHER { get; set; }
        public string Ten_VOUCHER { get; set; }
        public Nullable<double> PhanTramGiam { get; set; }
        public Nullable<double> DonToiThieu { get; set; }
        public Nullable<double> GiamToiDa { get; set; }
        public Nullable<int> SoLuongVOUCHER { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOUCHER_KHACHHANG> VOUCHER_KHACHHANG { get; set; }
    }
}
